### ISSUE TITLE
suggestion: export-all-bookmarks

### ISSUE THREAD

**Issue by ikki4** [gabrielbarros/export-all-extensions#3]
Cara, muito boa essa sua extensão! Não manjo mto de programação, então se vc estiver aceitando sugestões de projetos, eu tenho uma: já pensou em criar uma extensão igual essa, mas que ao invés de baixar um arquivo html com as extensões, ele baixaria um arquivo html com os favoritos? Eu sei que dá pra exportar os favoritos manualmente no Gerenciador de Favoritos, então essa minha sugestão seria basicamente automatizar esse processo. Abraço!

-----------------------------------------------------------------------------------------------------------------
for non-portuguese speakers:

Your extension is great! I don't know if you are taking any suggestions for new extensions, but if you are, I'd love to have an extension just like this one, but instead of downloading an html file with all extensions, it would download an html file with all bookmarks (so basically the extension would automate the manual process of exporting bookmarks)

**Comment by gabrielbarros** [comment]
Oi, @ikki4. Que bom que gostou da extensão. 

> já pensou em criar uma extensão igual essa, mas que ao invés de baixar um arquivo html com as extensões, ele baixaria um arquivo html com os favoritos

Já pensei! Mas só tem um problema: a API dos favoritos não permite o ler favicon dos links. Então na hora de importar o arquivo, todos os links ficariam sem os ícones.

**Comment by ikki4** [comment]
@gabrielbarros eu dei uma pesquisada rápida aqui, e encontrei uma extensão que identifica o icon/favicon de um link. Será que o código dessa extensão seria útil pra vc?

https://github.com/BlackGlory/favicon-detector

**Comment by ikki4** [comment]
Entendi. Então realmente não há nada que se possa fazer, exceto esperar que a Google libere o favicon na API dos favoritos. Obrigado por responder e me explicar melhor essa situação!
